"""save_report: write accumulated report + follow-ups to .md and .html files."""

import re
from datetime import datetime
from pathlib import Path

import markdown as md_lib
from pydantic import BaseModel


class SaveReportResult(BaseModel):
    md_path: str
    html_path: str
    filename_stem: str
    saved_at: str


_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{title}</title>
  <style>
    body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
            line-height: 1.6; max-width: 960px; margin: 40px auto; padding: 0 20px; color: #24292e; }}
    h1, h2, h3, h4 {{ margin-top: 1.5em; border-bottom: 1px solid #eaecef; padding-bottom: 0.3em; }}
    h1 {{ border-bottom: 2px solid #0366d6; }}
    table {{ border-collapse: collapse; width: 100%; margin: 1em 0; }}
    th, td {{ border: 1px solid #dfe2e5; padding: 8px 13px; text-align: left; }}
    th {{ background: #f6f8fa; font-weight: 600; }}
    tr:nth-child(even) {{ background: #fafbfc; }}
    code {{ background: #f3f4f5; padding: 2px 5px; border-radius: 3px;
            font-family: "SFMono-Regular", Consolas, monospace; font-size: 0.9em; }}
    pre {{ background: #f6f8fa; padding: 16px; border-radius: 6px; overflow-x: auto; }}
    pre code {{ background: none; padding: 0; }}
    blockquote {{ border-left: 4px solid #dfe2e5; margin: 0 0 1em 0;
                  padding: 0.5em 1em; color: #6a737d; background: #f9f9f9; }}
    a {{ color: #0366d6; text-decoration: none; }}
    a:hover {{ text-decoration: underline; }}
    hr {{ border: none; border-top: 1px solid #eaecef; margin: 2em 0; }}
    .report-footer {{ color: #6a737d; font-size: 0.85em; margin-top: 3em;
                      border-top: 1px solid #eaecef; padding-top: 1em; }}
  </style>
</head>
<body>
{body}
<div class="report-footer">Generated by infra-advisor MCP &middot; {saved_at}</div>
</body>
</html>
"""


def _slugify(text: str, max_words: int = 5) -> str:
    clean = re.sub(r'[#*>`\[\]()\\_]', ' ', text)
    words = re.findall(r'[a-zA-Z0-9]+', clean)
    # Skip generic report header words
    skip = {"ai", "infrastructure", "advisor", "report", "your", "request"}
    meaningful = [w.lower() for w in words if w.lower() not in skip]
    return '_'.join(meaningful[:max_words])


def _extract_title(report_content: str) -> str:
    for line in report_content.splitlines():
        stripped = line.strip()
        if stripped.startswith('# '):
            return stripped[2:].strip()
    return "AI Infrastructure Report"


def save_report(
    report_content: str,
    followups: list[str] | None = None,
    filename: str | None = None,
    output_dir: str = "reports",
) -> SaveReportResult:
    """Write the accumulated report and any follow-up answers to .md and .html files.

    Call this when you are satisfied with the report — this is the finalize action.
    The caller (Claude) accumulates follow-up answers and passes them all at once.

    Args:
        report_content: Main report markdown from generate_full_report.
        followups: Follow-up answer strings from generate_followup_answer, in order.
                   Each is appended as its own section after the main report.
        filename: Base filename without extension. Defaults to timestamp + content slug.
        output_dir: Directory to write files into. Created if it does not exist.
    """
    now = datetime.now()
    saved_at = now.strftime("%Y-%m-%d %H:%M:%S")

    parts = [report_content.rstrip()]
    if followups:
        parts.append("\n\n---\n\n## Follow-up Questions\n")
        for fu in followups:
            parts.append(f"\n{fu.strip()}\n")
    combined_md = "\n".join(parts)

    if not filename:
        slug = _slugify(report_content)
        filename = now.strftime("%Y%m%d_%H%M%S") + (f"_{slug}" if slug else "")

    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    md_path = out / f"{filename}.md"
    html_path = out / f"{filename}.html"

    md_path.write_text(combined_md, encoding="utf-8")

    title = _extract_title(report_content)
    html_body = md_lib.markdown(
        combined_md,
        extensions=["tables", "fenced_code"],
    )
    html = _HTML_TEMPLATE.format(title=title, body=html_body, saved_at=saved_at)
    html_path.write_text(html, encoding="utf-8")

    return SaveReportResult(
        md_path=str(md_path),
        html_path=str(html_path),
        filename_stem=filename,
        saved_at=saved_at,
    )
